export const MODULE_ID = "dw-automation";

export const SETTINGS = {
  ENABLE_NPC_GENERATOR: "enableNpcGenerator",
  ENABLE_MONSTER_GENERATOR: "enableMonsterGenerator",
  ENABLE_ATTACK_ASSISTANT: "enableAttackAssistant",
  MELEE_MOVE_NAMES: "meleeMoveNames",
  RANGED_MOVE_NAMES: "rangedMoveNames",
  MELEE_WEAPON_TAGS: "meleeWeaponTags",
  RANGED_WEAPON_TAGS: "rangedWeaponTags",
  ENABLED_DAMAGE_TAGS: "enabledDamageTags",
  SPECIAL_ATTACK_MOVES: "specialAttackMoves",
  ENABLE_SPELLCASTING_ASSISTANT: "enableSpellcastingAssistant",
  CAST_SPELL_MOVE_NAMES: "castSpellMoveNames",
  ONGOING_SPELLS: "ongoingSpells",
  SPELL_AUGMENTATION_MOVE_NAMES: "spellAugmentationMoveNames",
  CAST_PARTIAL_REVOKE_INDEX: "castPartialRevokeIndex",
  CAST_PARTIAL_PENALTY_INDEX: "castPartialPenaltyIndex",
  ENABLE_HIT_TRIGGER_ASSISTANT: "enableHitTriggerAssistant",
  HIT_TRIGGER_MOVES: "hitTriggerMoves",
  INDOMITABLE_MOVE_NAMES: "indomitableMoveNames",
  ENABLE_HEALING_ASSISTANT: "enableHealingAssistant",
  HEALING_MOVES: "healingMoves",
  HOSPITALLER_MOVES: "hospitallerMoves",
  ENABLE_MOVE_UPGRADE_ASSISTANT: "enableMoveUpgradeAssistant",
  MOVE_UPGRADES: "moveUpgrades",
  DAMAGE_REDUCTION_MOVES: "damageReductionMoves",
  CONDITIONAL_DAMAGE_MOVES: "conditionalDamageMoves",
  SUPERIOR_WARRIOR_MOVE_NAMES: "superiorWarriorMoveNames",
  ENABLE_DRUID_ASSISTANT: "enableDruidAssistant",
  DRUID_BALANCE_MOVE_NAMES: "druidBalanceMoveNames",
  DRUID_SHAPESHIFTER_MOVE_NAMES: "druidShapeshifterMoveNames",
  DRUID_DAMAGE_DIE_MOVES: "druidDamageDieMoves",
  DRUID_SHED_MOVE_NAMES: "druidShedMoveNames",
  DRUID_FORMCRAFTER_MOVE_NAMES: "druidFormcrafterMoveNames",
  DRUID_FORMSHAPER_MOVE_NAMES: "druidFormshaperMoveNames",
  ENABLE_NOTE_MOVES: "enableNoteMoves",
  NOTE_MOVE_NAMES: "noteMoveNames"
};
