import { registerSettings } from "./settings.js";
import { registerNpcGenerator } from "./features/npc-generator.js";
import { registerMonsterGenerator } from "./features/monster-generator.js";
import { registerAttackAssistant } from "./features/attack-assistant.js";
import { registerSpellcastingAssistant } from "./features/spellcasting.js";
import { registerRollWrapper } from "./lib/roll-wrapper.js";
import { registerHitTriggerAssistant } from "./features/hit-trigger.js";
import { registerHealingAssistant } from "./features/healing.js";
import { registerMoveUpgradeAssistant } from "./features/move-upgrades.js";
import { registerDruidAssistant } from "./features/druid.js";
import { registerClassInfoTab } from "./features/class-info-tab.js";
import { registerNoteMoves } from "./features/note-moves.js";
import { registerArmorAssistant } from "./features/armor-assistant.js";
import { registerUnderdogAssistant } from "./features/underdog.js";
import { registerLevelUpInfo } from "./features/level-up-info.js";
import { registerClassGrantAssistant } from "./features/class-grant.js";
import { registerCommandAssistant } from "./features/command.js";
import { registerWellTrainedAssistant } from "./features/well-trained.js";
import { registerUnnaturalAllyAssistant } from "./features/unnatural-ally.js";
import { registerAidOrInterfereAssistant } from "./features/aid-or-interfere.js";
import { registerArcaneArtAssistant } from "./features/arcane-art.js";
import { registerSelfForwardAssistant } from "./features/self-forward.js";
import { registerBarbarianAssistant } from "./features/barbarian.js";
import { registerSpellPreparationAssistant } from "./features/spell-preparation.js";
import { registerSpellDiscountAssistant } from "./features/spell-discount.js";
import { registerSpellbookExpansionAssistant } from "./features/spellbook-expansion.js";
import { registerCounterspellAssistant } from "./features/counterspell.js";
import { registerIAmTheLawAssistant } from "./features/i-am-the-law.js";
import { registerKnowItAllAssistant } from "./features/know-it-all.js";
import { registerVitalsAssistant } from "./features/vitals-assistant.js";
import { registerEncumbranceAssistant } from "./features/encumbrance.js";
import { registerRecruitAssistant } from "./features/recruit.js";
import { registerBolsterAssistant } from "./features/bolster.js";
import { registerBurningBrandAssistant } from "./features/burning-brand.js";
import { registerDefendAssistant } from "./features/defend.js";
import { registerTwiceAsBrightAssistant } from "./features/twice-as-bright.js";
import { registerBurningBridgesAssistant } from "./features/burning-bridges.js";
import { registerTwinHornWildfireAssistant } from "./features/twin-horn-wildfire.js";
import { registerBurningRingOfFireAssistant } from "./features/burning-ring-of-fire.js";
import { registerSignatureWeaponAssistant } from "./features/signature-weapon.js";
import { registerIronHideAssistant } from "./features/iron-hide.js";
import { registerMercilessAssistant } from "./features/merciless.js";
import { registerInterrogatorAssistant } from "./features/interrogator.js";
import { registerPreciseWeaponAssistant } from "./features/precise-weapon.js";

Hooks.once("init", () => {
  registerSettings();
});

// game.dungeonworld.ItemDw(및 다른 시스템/모듈이 등록해두는 전역들)가 전부
// 준비된 뒤에 감싸야 안전하므로 ready에서 등록한다.
Hooks.once("ready", () => {
  registerRollWrapper();
});

registerNpcGenerator();
registerMonsterGenerator();
registerAttackAssistant();
registerSpellcastingAssistant();
registerHitTriggerAssistant();
registerHealingAssistant();
registerMoveUpgradeAssistant();
registerDruidAssistant();
registerClassInfoTab();
registerNoteMoves();
registerArmorAssistant();
registerUnderdogAssistant();
registerLevelUpInfo();
registerClassGrantAssistant();
registerCommandAssistant();
registerWellTrainedAssistant();
registerUnnaturalAllyAssistant();
registerAidOrInterfereAssistant();
registerArcaneArtAssistant();
registerSelfForwardAssistant();
registerBarbarianAssistant();
registerSpellPreparationAssistant();
registerSpellDiscountAssistant();
registerSpellbookExpansionAssistant();
registerCounterspellAssistant();
registerIAmTheLawAssistant();
registerKnowItAllAssistant();
registerVitalsAssistant();
registerEncumbranceAssistant();
registerRecruitAssistant();
registerBolsterAssistant();
registerBurningBrandAssistant();
registerDefendAssistant();
registerTwiceAsBrightAssistant();
registerBurningBridgesAssistant();
registerTwinHornWildfireAssistant();
registerBurningRingOfFireAssistant();
registerSignatureWeaponAssistant();
registerIronHideAssistant();
registerMercilessAssistant();
registerInterrogatorAssistant();
registerPreciseWeaponAssistant();
